model_name: pointnet2_original # Name of the specific model to load
model_type: pointnet2
dataset: ahn_aerial
task: segmentation
experiment_name: ahn_small #experiment name, used for saving outputs


defaults:
  - task: segmentation # Task performed (segmentation, classification etc...)
    optional: True
  - model_type: pointnet2 # Type of model to use, e.g. pointnet2, rsconv etc...
    optional: True
  - dataset: ahn_aerial
    optional: True

  - training
  - eval

  - models: ${defaults.0.task}/${defaults.1.model_type}
  - data: ${defaults.0.task}/${defaults.2.dataset}
  - sota # Contains current SOTA results on different datasets (extracted from papers !).
  - hydra/job_logging: custom



# Those arguments within experiment defines which model, dataset and task to be created for benchmarking
# parameters for Weights and Biases
wandb:
  project: ahn-pn2
  log: False

# parameters for TensorBoard Visualization
tensorboard:
  log: True
