defaults:
  - task: segmentation # Task performed (segmentation, classification etc...)
    optional: True
  - model_type: randlanet # Type of model to use, e.g. pointnet2, rsconv etc...
    optional: True
  - dataset: s3dis
    optional: True

  - training: default
  - eval

  - models: ${defaults.0.task}/${defaults.1.model_type}
  - data: ${defaults.0.task}/${defaults.2.dataset}
  - sota # Contains current SOTA results on different datasets (extracted from papers !).
  - hydra/job_logging: custom

model_name: Randlanet_Res # Name of the specific model to load

pretty_print: False
