# Those arguments defines the training hyper-parameters
training:
    shuffle: False
    num_workers: 2
    batch_size: 1
    cuda: True
    precompute_multi_scale: False # Compute multiscate features on cpu for faster training / inference
    epochs: 1000
    optimizer:
        class: SGD
        params:
            momentum: 0.98
            weight_decay: 1e-3
            lr: 0.01
    learning_rate:
        scheduler_type: "step_decay"
        base_lr: ${optimizer.params.lr}
        lr_decay: 0.5
        decay_step: 200000
        lr_clip: 1e-5
    weight_name: "acc" # Used during resume, select with model to load from [miou, macc, acc..., latest]
    enable_cudnn: True
    checkpoint_dir: "outputs/checkpoints"
    resume: True
